#!/usr/bin/env -S ANSIBLE_STDOUT_CALLBACK=debug ansible-playbook --step
- hosts:
  user:
  # gather_facts: no
  # pre_tasks:
  #   - name: 'install python'
  #     raw: sudo apt-get -y install python
  tasks:
