version: "2.0"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
      args:  # TODO define in .env
        UID: $UID
        GID: $GID
    volumes:
      - ./:/opt/app
